"""empty message

Revision ID: b7cfc79c8bb8
Revises: 34ac3f9fe54b
Create Date: 2025-04-25 16:45:52.435520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7cfc79c8bb8'
down_revision = '34ac3f9fe54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
